### ISSUE TITLE
Hello, are you still into programming?

### ISSUE THREAD

**Issue by princes21** [Deudly/deudly.github.com#1]
I've been using your sandbox mode for LoL and it was the only working sandbox app for me... I wanted to ask, are you still developing it? I wanted to request some new features and bugs...  But I saw you closed commenting on there, I assumed you stopped improving and developing it. So I just wanted to make sure by asking. I really love your project.

**Comment by Deudly** [comment]
The sandbox downloader tool got discontinued because there are other more powerful alternatives. And yeah, Im still into programming.

> Sorry for answering one year later, I dont usually check the issues of this repo
